#
# MGRX test programs makefile for LINUX/X11. Uses GNU make.
#
.PHONY : clean setsuid

GRXVX11=y

include ../makedefs.grx

INCDIR=  -I../include

# Enable this line for static linked test progs (default)
MGRXX = ../lib/$(GRX_LIB_SUBDIR)/libmgrxX.a
# or this if you've already installed the shared libs
#MGRXX = -L../lib/$(GRX_LIB_SUBDIR) -lmgrxX

ifeq ($(SET_XSUIDROOT),y)
EXECBITS = 4755
else
EXECBITS = 0755
endif

ADDON_LIBS=

ifeq ($(USE_XF86DGA_DRIVER),y)
  ADDON_LIBS += -lXxf86dga -lXext
endif

ifeq ($(HAVE_LIBTIFF),y)
  ADDON_LIBS += -ltiff
endif

ifeq ($(HAVE_LIBJPEG),y)
  ADDON_LIBS += -ljpeg
endif

ifeq ($(HAVE_LIBPNG),y)
  ADDON_LIBS += -lpng
endif

ifeq ($(NEED_ZLIB),y)
  ADDON_LIBS += -lz
endif

LIBS= $(MGRXX) $(ADDON_LIBS) $(X11LIBS) -lm

ifndef   DEBUG
LDOPT += -s
endif

PROGS=  xarctest     \
	xbb1test     \
	xblittest    \
	xcirctest    \
	xcliptest    \
	xcolorops    \
	xcurstest    \
	xfontdemo    \
	xfonttest    \
	ximgtest     \
	xjpgtest     \
	xkeys        \
	xlife        \
	xlinetest    \
	xmemtest     \
	xmousetst    \
	xpcirctst    \
	xpnmtest     \
	xpngtest     \
	xpolytest    \
	xrgbtest     \
	xsbctest     \
	xscroltst    \
	xspeedtst    \
	xtextpatt    \
	xwinclip     \
	xwintest     \
	xbiggtest

all: $(PROGS) xdemomgrx xdemointl

xdemomgrx: demomgrx.o gfaz.o $(MGRXX)
	$(CC) $(LDOPT) -o xdemomgrx demomgrx.o gfaz.o $(LIBS)
	chmod $(EXECBITS) xdemomgrx

xdemointl: demointl.o gfaz.o $(MGRXX)
	$(CC) $(LDOPT) -o xdemointl demointl.o gfaz.o $(LIBS)
	chmod $(EXECBITS) xdemointl

$(PROGS): x%: %.o $(MGRXX)
	$(CC) $(LDOPT) -o $@ $*.o $(LIBS)
	chmod $(EXECBITS) $@

$(PROGS:x%=%.o): %.o : %.c
	$(CC) -c $(CCOPT) -D__XWIN__ $(INCDIR) $*.c -o $*.o

.c.o:
	$(CC) -c $(CCOPT) -D__XWIN__ $(INCDIR) $*.c

.c.s:
	$(CC) -S $(CCOPT) $(INCDIR) $*.c

clean:
	rm -f *.o $(PROGS) xdemomgrx xdemointl

setsuid: $(PROGS) xdemomgrx xdemointl
ifeq ($(SET_XSUIDROOT),y)
	chown root $(PROGS) xdemomgrx xdemointl
	chmod $(EXECBITS) $(PROGS) xdemomgrx xdemointl
else
	@echo "Nothing to do, SET_XSUIDROOT is not set to 'y' in makedefs.grx"
endif

depend.new:
	$(CC) -MM $(CCOPT) $(INCDIR) $(PROGS:x%=%.c) > depend.new

include depend.gnu
