#
# GRX test programs makefile for LINUX/X11. Uses GNU make.
#

GRXVX11=y

include ../makedefs.grx

INCDIR=  -I../include

# Enable this line for static linked test progs (default)
GRX20X = ../lib/$(GRX_LIB_SUBDIR)/libgrx20X.a
# or this if you've already installed the shared libs
#GRX20X = -L../lib/$(GRX_LIB_SUBDIR) -lgrx20X

ADDON_LIBS=

ifeq ($(HAVE_LIBTIFF),y)
  ADDON_LIBS += -ltiff
endif

ifeq ($(HAVE_LIBJPEG),y)
  ADDON_LIBS += -ljpeg
endif

ifeq ($(HAVE_LIBPNG),y)
  ADDON_LIBS += -lpng
endif

ifeq ($(NEED_ZLIB),y)
  ADDON_LIBS += -lz
endif

LIBS= $(GRX20X) $(ADDON_LIBS) $(X11LIBS) -lm

ifndef   DEBUG
LDOPT += -s
endif

PROGS=  xarctest     \
	xbb1test     \
	xblittest    \
	xcirctest    \
	xcliptest    \
	xcolorops    \
	xcurstest    \
	xfonttest    \
	ximgtest     \
	xkeys        \
	xlife        \
	xlinetest    \
	xmousetst    \
	xpcirctst    \
	xpnmtest     \
	xpngtest     \
	xpolytest    \
	xrgbtest     \
	xsbctest     \
	xscroltst    \
	xspeedtst    \
	xtextpatt    \
	xwinclip     \
	xwintest

all: $(PROGS) xdemogrx

xdemogrx: demogrx.o gfaz.o
	$(CC) $(LDOPT) -o xdemogrx demogrx.o gfaz.o $(LIBS)

$(PROGS): x%: %.o ../lib/$(GRX_LIB_SUBDIR)/libgrx20X.a
	$(CC) $(LDOPT) -o $@ $*.o $(LIBS)

$(PROGS:x%=%.o): %.o : %.c
	$(CC) -c $(CCOPT) -D__XWIN__ $(INCDIR) $*.c -o $*.o

.c.o:
	$(CC) -c $(CCOPT) -D__XWIN__ $(INCDIR) $*.c

.c.s:
	$(CC) -S $(CCOPT) $(INCDIR) $*.c

clean:
	rm -f *.o $(PROGS) xdemogrx

depend.new:
	$(CC) -MM $(CCOPT) $(INCDIR) $(PROGS:x%=%.c) > depend.new

include depend.gnu
