#
# GRX 2.0 test programs makefile for Turbo C. Uses Turbo C make.
#
.AUTODEPEND

!include "../makedefs.bcc"

INCDIR= -I../include -I$(BCCROOT)\include
LIBDIR= -L$(BCCROOT)/lib

GRX20ST = ../lib/$(GRX_LIB_SUBDIR)/grx20$(MODEL).lib

PROGS=                  \
	arctest.exe     \
	blittest.exe    \
	circtest.exe    \
	cliptest.exe    \
	colorops.exe    \
	curstest.exe    \
	fnt2c.exe       \
	fonttest.exe    \
	imgtest.exe     \
	life.exe        \
	linetest.exe    \
	modtst16.exe    \
	mousetst.exe    \
	pcirctst.exe    \
	pnmtest.exe     \
	polytest.exe    \
	rgbtest.exe     \
	sbctest.exe     \
	scroltst.exe    \
	spdtst16.exe    \
	textpatt.exe    \
	winclip.exe     \
	wintest.exe

all:    $(PROGS) ..\bin\modtst16.exe ..\bin\fnt2c16.exe

clean:
	if exist *.obj del *.obj
	if exist *.exe del *.exe

..\bin\modtst16.exe: modtst16.exe
	copy modtst16.exe ..\bin
	-$(STRIP) ..\bin\modtst16.exe

..\bin\fnt2c16.exe: fnt2c16.exe
	copy fnt2c16.exe ..\bin
	-$(STRIP) ..\bin\fnt2c16.exe

modtst16.exe: modetest.obj
	$(BCC) $(LIBDIR) $(LDOPT) -n. -emodtst16 modetest.obj $(GRX20ST)

spdtst16.exe: speedtst.obj
	$(BCC) $(LIBDIR) $(LDOPT) -n. -espdtst16 speedtst.obj $(GRX20ST)

fnt2c16.exe: fnt2c.obj
	$(BCC) $(LIBDIR) $(LDOPT) -n. -efnt2c16 fnt2c.obj $(GRX20ST)

.obj.exe:
	$(BCC) $(LIBDIR) $(LDOPT) -n. -e$* $*.obj $(GRX20ST)

.c.obj:
	$(BCC) -c $(CCOPT) $(INCDIR) -o$*.obj $*.c

