#
# GRX 2.0 test programs makefile for LINUX/svgalib. Uses GNU make.
#

include  ../makedefs.gnu
INCDIR=  -I../include

CCOPT += -pipe

# Enable this line for static linked test progs (default)
GRX20 = ../lib/$(GRX_LIB_SUBDIR)/libgrx20.a
# or this if you've already installed the shared libs
#GRX20 = -L../lib/$(GRX_LIB_SUBDIR) -lgrx20

ADDON_LIBS= -lvga

ifeq ($(HAVE_LIBTIFF),y)
  ADDON_LIBS += -ltiff
endif

ifeq ($(HAVE_LIBJPEG),y)
  ADDON_LIBS += -ljpeg
endif

ifeq ($(NEED_ZLIB),y)
  ADDON_LIBS += -lz
endif

LIBS= $(GRX20) $(ADDON_LIBS) -lm

PROGS=              \
	arctest     \
	blittest    \
	circtest    \
	cliptest    \
	colorops    \
	curstest    \
	fnt2c       \
	fonttest    \
	imgtest     \
	keys        \
	life        \
	linetest    \
	modetest    \
	mousetst    \
	pcirctst    \
	pnmtest     \
	polytest    \
	rgbtest     \
	sbctest     \
	scroltst    \
	speedtst    \
	textpatt    \
	winclip     \
	wintest

all:    $(PROGS) demogrx

modetest: modetest.o
	$(CC) $(LDOPT) -o modetest modetest.o $(LIBS)
	$(STRIP) modetest
	chmod 4755 modetest
	cp modetest ../bin
	chmod 4755 ../bin/modetest

fnt2c: fnt2c.o
	$(CC) $(LDOPT) -o fnt2c fnt2c.o $(LIBS)
	$(STRIP) fnt2c
	cp fnt2c ../bin

demogrx: demogrx.o gfaz.o
	$(CC) $(LDOPT) -o demogrx demogrx.o gfaz.o $(LIBS)
	chmod 4755 demogrx

.o:
	$(CC) $(LDOPT) -o $* $*.o $(LIBS)
	chmod 4755 $*

.oo:
	$(CC) $(LDOPT) -o $* $*.o $(LIBS)
	$(STRIP) $*

.c.o:
	$(CC) -c $(CCOPT) $(INCDIR) $*.c -o $*.o

.c.s:
	$(CC) -S $(CCOPT) $(INCDIR) $*.c

clean:
	rm -f *.o $(PROGS)

depend.new:
	$(CC) -MM $(CCOPT) $(INCDIR) $(PROGS:=.c) >depend.new

$(PROGS): % : %.o ../lib/$(GRX_LIB_SUBDIR)/libgrx20.a

include depend.gnu
