#
# MGRX test programs makefile for Mingw. Uses GNU make.
#
.SUFFIXES: .exe
.PHONY: clean install uninstall

GRXVW32=y

include ../makedefs.grx

INCDIR=  -I../include
MGRX = ../lib/$(GRX_LIB_SUBDIR)/libmgrx.a

ifeq ($(HAVE_LIBTIFF),y)
  ADDON_LIBS += -ltiff
endif

ifeq ($(HAVE_LIBJPEG),y)
  ADDON_LIBS += -ljpeg
endif

ifeq ($(HAVE_LIBPNG),y)
  ADDON_LIBS += -lpng
endif

ifeq ($(NEED_ZLIB),y)
  ADDON_LIBS += -lz
endif

LIBS= $(MGRX) $(ADDON_LIBS)

PROGS=  arctest.exe     \
	bb1test.exe     \
	blittest.exe    \
	circtest.exe    \
	cliptest.exe    \
	colorops.exe    \
	curstest.exe    \
	fontdemo.exe    \
	fonttest.exe    \
	imgtest.exe     \
	jpgtest.exe     \
	keys.exe        \
	life.exe        \
	linetest.exe    \
	mousetst.exe    \
	pcirctst.exe    \
	pnmtest.exe     \
	pngtest.exe     \
	polytest.exe    \
	rgbtest.exe     \
	sbctest.exe     \
	scroltst.exe    \
	textpatt.exe    \
	winclip.exe     \
	wintest.exe     \
	biggtest.exe

all: 	$(PROGS) \
	demomgrx.exe \
	demointl.exe \
	speedtst.exe \
	memtest.exe

demomgrx.exe: demomgrx.o gfaz.o $(MGRX)
	$(CC) $(LDOPT) -o demomgrx.exe demomgrx.o gfaz.o $(LIBS) -lm -mwindows

demointl.exe: demointl.o gfaz.o $(MGRX)
	$(CC) $(LDOPT) -o demointl.exe demointl.o gfaz.o $(LIBS) -lm -mwindows

speedtst.exe: speedtst.o $(MGRX)
	$(CC) $(LDOPT) -o speedtst.exe speedtst.o $(LIBS) -lm -mwindows -mconsole

memtest.exe: memtest.o $(MGRX)
	$(CC) $(LDOPT) -o memtest.exe memtest.o $(LIBS) -lm -mwindows -mconsole

$(PROGS): %.exe : %.o $(MGRX)
	$(CC) $(LDOPT) -o $*.exe $*.o $(LIBS) -lm -mwindows

.c.o:
	$(CC) -c $(CCOPT) $(INCDIR) $*.c -o $*.o

.c.s:
	$(CC) -S $(CCOPT) $(INCDIR) $*.c

clean:
	if exist *.o del *.o
	if exist *.exe del *.exe

depend.new:
	$(CC) -MM $(CCOPT) $(INCDIR) $(PROGS:.exe=.c) >depend.new

include depend.gnu
