language: bash
sudo: required
dist: bionic
env:
- OS=ubuntu ARCH=amd64 DIST=focal
- OS=ubuntu ARCH=i386 DIST=focal
- OS=ubuntu ARCH=arm64 DIST=focal
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository --yes ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes debhelper pbuilder-ev3dev gobject-introspection
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-focal
script:
- pbuilder-ev3dev dev-build
