language: bash
sudo: required
dist: trusty
env:
- OS=ubuntu ARCH=amd64 DIST=zesty
- OS=ubuntu ARCH=i386 DIST=zesty
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository --yes ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes pbuilder-ev3dev gobject-introspection
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-zesty
script:
- pbuilder-ev3dev build
