#
# GRX test programs makefile for Mingw
# Uses GNU make.
#
.SUFFIXES: .exe
.PHONY: clean install uninstall

GRXVW32=y

include ../../makedefs.grx

INCDIR=  -I../../include
GRX20 = ../../lib/$(GRX_LIB_SUBDIR)/libgrx20.a

#ifeq ($(HAVE_LIBTIFF),y)
#  ADDON_LIBS += -ltiff
#endif

#ifeq ($(HAVE_LIBJPEG),y)
#  ADDON_LIBS += -ljpeg
#endif

#ifeq ($(NEED_ZLIB),y)
#  ADDON_LIBS += -lz
#endif

LIBS= $(GRX20) $(ADDON_LIBS)

PROGS=                  \
	bccbgi.exe       

all: 	$(PROGS) \

$(PROGS): %.exe : %.o $(GRX20)
	$(CC) $(LDOPT) -o $*.exe $*.o $(LIBS) -lm -mwindows -mconsole

.c.o:
	$(CC) -c $(CCOPT) $(INCDIR) $*.c -o $*.o

.c.s:
	$(CC) -S $(CCOPT) $(INCDIR) $*.c

clean:
	if exist *.o del *.o
	if exist *.exe del *.exe

#depend.new:
#	$(CC) -MM $(CCOPT) $(INCDIR) $(PROGS:.exe=.c) >depend.new

#include depend.gnu
