#
# GRX 2.0 Library Makefile for DJGPP v2.
# Needs GNU Make.
#
# This file just reads the basic system setup and
# prepares the TAG variable.  All real work is in
# files shared between DJGPP v1 && DJGPP v2.

include ../makedefs.gnu
include ../makedefs.dj2

ifndef DEBUG
ifndef PROFILE
CCOPT += -fomit-frame-pointer
endif
endif

TAG = $(DOS_DJGPP_V2)

include ./makebase.dj
